"""Config loading from TOML."""
from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path

from textual.color import Color


def _validate_color(value: str, field_name: str) -> str:
    """Raise ValueError with a clear message if value is not a parseable Textual color."""
    try:
        Color.parse(value)
    except Exception as exc:
        raise ValueError(
            f"[app] {field_name} = {value!r} is not a valid color: {exc}"
        ) from exc
    return value


@dataclass
class PaneConfig:
    id: str = ""             # auto-generated by parent if empty
    type: str = "command"    # "command" | "system" | "tabs" | "column" | "row"
    title: str = ""
    width: str = "1fr"
    height: str = "1fr"      # used when pane is inside a column
    command: str | None = None
    refresh: int = 0         # 0 = run once (watcher); >0 = restart N seconds after exit
    min_width: int = 0       # collapse pane when terminal narrower than this
    cwd: str | None = None   # working directory for the command
    scrollable: bool = False         # wrap output in a scrollable container
    follow: bool = False             # auto-scroll to bottom on new output (only if already at bottom)
    interactive: bool = False        # allow hover/focus/click-select and Tab cycling
    restart_on_resize: bool = False  # restart the command when the terminal is resized
    tabs: list["PaneConfig"] = field(default_factory=list)
    panes: list["PaneConfig"] = field(default_factory=list)  # sub-panes for column/row types

    @property
    def is_interactive(self) -> bool:
        """True if this pane (or any child) is interactive or scrollable."""
        if self.interactive or self.scrollable:
            return True
        return any(t.is_interactive for t in self.tabs) or any(p.is_interactive for p in self.panes)


@dataclass
class RowConfig:
    height: str = "1fr"
    panes: list[PaneConfig] = field(default_factory=list)


@dataclass
class AppConfig:
    title: str = "topiary"
    refresh_rate_hz: float = 20.0
    background: str = "transparent"
    foreground: str = ""
    rows: list[RowConfig] = field(default_factory=list)


def _parse_pane(raw: dict) -> PaneConfig:
    raw = dict(raw)
    tabs_raw = raw.pop("tabs", [])
    panes_raw = raw.pop("panes", [])
    tabs = [_parse_pane(t) for t in tabs_raw]   # recursive — tabs are full PaneConfigs
    panes = [_parse_pane(p) for p in panes_raw]  # recursive — column sub-panes
    return PaneConfig(**raw, tabs=tabs, panes=panes)


def load_config(path: Path) -> AppConfig:
    with open(path, "rb") as f:
        data = tomllib.load(f)

    app_kw = {k: v for k, v in data.get("app", {}).items()}
    for color_field in ("background", "foreground"):
        if color_field in app_kw and app_kw[color_field]:
            _validate_color(app_kw[color_field], color_field)
    rows = []
    for row_raw in data.get("rows", []):
        row_raw = dict(row_raw)
        panes_raw = row_raw.pop("panes", [])
        panes = [_parse_pane(p) for p in panes_raw]
        rows.append(RowConfig(**row_raw, panes=panes))

    return AppConfig(**app_kw, rows=rows)
